'use strict';(function(modules){var installedModules={};function __webpack_require__(moduleId){if(installedModules[moduleId])
return installedModules[moduleId].exports;var module=installedModules[moduleId]={exports:{},id:moduleId,loaded:false};modules[moduleId].call(module.exports,module,module.exports,__webpack_require__);module.loaded=true;return module.exports;}
__webpack_require__.m=modules;__webpack_require__.c=installedModules;__webpack_require__.p="";return __webpack_require__(0);})([function(module,exports,__webpack_require__){'use strict';var menu=__webpack_require__(1);var swipe=__webpack_require__(2);var article=__webpack_require__(4);function init(){menu.init();swipe.init();article.init();}
if(document.readyState!=='loading'){init();}else{document.addEventListener('readystatechange',function(){if(document.readyState==='interactive'){init();}});}},function(module,exports){'use strict';Object.defineProperty(exports,"__esModule",{value:true});exports.init=init;function init(){var open=document.querySelector('.js-menu-open');if(open){open.addEventListener('click',openMenu);}
var close=document.querySelector('.js-menu-close');if(close){close.addEventListener('click',closeMenu);}
var overlay=document.querySelector('.js-menu-bg');if(overlay){overlay.addEventListener('click',closeMenu);}}
function openMenu(){var menu=document.querySelector('.js-menu');var overlay=document.querySelector('.js-menu-bg');document.body.classList.add('overflow-y-hidden');menu.classList.add('menu-open');overlay.style.display='block';}
function closeMenu(){var menu=document.querySelector('.js-menu');var overlay=document.querySelector('.js-menu-bg');document.body.classList.remove('overflow-y-hidden');menu.classList.remove('menu-open');overlay.style.display='none';}},function(module,exports,__webpack_require__){'use strict';Object.defineProperty(exports,"__esModule",{value:true});exports.init=init;var _utils=__webpack_require__(3);function swipe(el,callback){var touchdown=false;var originalPosition=null;var info=void 0;function swipeInfo(e){var x=e.pageX||e.touches[0].clientX;var y=e.pageY||e.touches[0].clientY;var dx=void 0,dy=void 0;dx=x>originalPosition.x?'right':'left';dy=y>originalPosition.y?'down':'up';return{direction:{x:dx,y:dy},offset:{x:x-originalPosition.x,y:originalPosition.y-y}};}
el.addEventListener('touchstart',handleStart);el.addEventListener('mousedown',handleStart);document.addEventListener('touchend',handleEnd);document.addEventListener('mouseup',handleEnd);el.addEventListener('touchmove',handleMove);el.addEventListener('mousemove',handleMove);function handleStart(e){touchdown=true;originalPosition={x:e.pageX||e.touches[0].clientX,y:e.pageY||e.touches[0].clientY};}
function handleEnd(e){if(!info)return;callback(info.direction,info.offset);info=null;touchdown=false;originalPosition=null;}
function handleMove(e){if(!touchdown)return;info=swipeInfo(e);}
return true;}
function handleSwipe(direction,offset){var threshold=50;if(Math.abs(offset.x)>threshold){direction.x==='left'?next():prev();}}
function next(){var el=document.querySelector('.js-swiper');var activeSlide=parseInt(el.getAttribute('data-active-slide'));if(activeSlide===el.children.length-1)return;var nextIndex=activeSlide?activeSlide+1:1;slideTo(nextIndex);el.setAttribute('data-active-slide',nextIndex);}
function prev(){var el=document.querySelector('.js-swiper');var activeSlide=parseInt(el.getAttribute('data-active-slide'));if(!activeSlide||activeSlide===0)return;var nextIndex=activeSlide-1;slideTo(nextIndex);el.setAttribute('data-active-slide',nextIndex);}
function slideTo(index){var el=document.querySelector('.js-swiper');var children=el.children;var childWidth=children[0].offsetWidth;el.style.transform='translateX(-'+(childWidth-16)*index+'px)';}
function init(){if(window.innerWidth>_utils.MEDIUM_SCREEN)return;var swiper=document.querySelector('.js-swiper');if(swiper)swipe(swiper,handleSwipe);}},function(module,exports){"use strict";Object.defineProperty(exports,"__esModule",{value:true});var MEDIUM_SCREEN=exports.MEDIUM_SCREEN=960;},function(module,exports,__webpack_require__){'use strict';Object.defineProperty(exports,"__esModule",{value:true});exports.init=init;var _utils=__webpack_require__(3);function _toConsumableArray(arr){if(Array.isArray(arr)){for(var i=0,arr2=Array(arr.length);i<arr.length;i++){arr2[i]=arr[i];}return arr2;}else{return Array.from(arr);}}
function handleScroll(e){var header=document.querySelector('.js-featured-image');if(!header)return;if(header.getBoundingClientRect().top<document.body.scrollTop){document.querySelector('header').classList.add('scrolled');}else{document.querySelector('header').classList.remove('scrolled');}}
function throttle(callback){var requestId=void 0;var later=function later(args){return function(){requestId=null;callback.apply(undefined,_toConsumableArray(args));};};var throttled=function throttled(){for(var _len=arguments.length,args=Array(_len),_key=0;_key<_len;_key++){args[_key]=arguments[_key];}
if(requestId===null||requestId===undefined){requestId=requestAnimationFrame(later(args));}};throttled.cancel=function(){return cancelAnimationFrame(requestId);};return throttled;}
function init(){if(window.innerWidth<_utils.MEDIUM_SCREEN)return;document.addEventListener('scroll',throttle(handleScroll));}}]);